title = "RbxTween"                                     # From Git
gitRepoUrl = "https://github.com/Ortho-Games/RbxTween" # From Git

gitSourceBranch = "main"
changelog = true
# classOrder = ["RbxTween", "FunctionUtil", "TableUtil", "MathUtil"]

[home]
enabled = true
includeReadme = false

# [navbar.logo]
# src = "favicon.ico"

[[home.features]]
title = "Documented & Organized"
description = "A curated and crafted library of tools with an online directory showcasing examples and search features."
# image = "/PuzzlePieces.png"

[[home.features]]
title = "Battle Tested"
description = "All the functions in this library were written and developed by developers who use them in the field."
# image = "/SandwichLogo.png"

[[home.features]]
title = "Typed & Intellisense"
description = "All the code in our library is typed and strict to allow for ease of use and maintains intellisense."
# image = "/Lightweight.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = "/favicon.ico"

# From git:
organizationName = "Ortho-Games"
projectName = "RbxTween"
url = "https://ortho-games.github.io"
baseUrl = "/RbxTween/"
tagline = "Luau essential tool library."

[navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2024 OrthoGames. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"
